server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: PRODUCT_SERVICE
          uri: lb://ORDER_SERVICE
          predicates:
            - Path=/order/**
        - id: PRODUCT_SERVICE
          uri: lb://PRODUCT_SERVICE
          predicates:
            - Path=/product/**
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
